/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dekstop;

import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;

/**
 *
 * @author Lusy
 */
public class pendaftaran extends javax.swing.JFrame {
    Connection con;
    Statement state;
    ResultSet rs;
    String sql;

    /**
     * Creates new form pendaftaran
     */
    public pendaftaran() {
        Container c = getContentPane(); 
        c.setBackground(new Color(255,204,204));
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        state = DB.st;
        
    }
    private void hapuslayar(){
        txtnama.setText("");
        txttempat.setText("");
        txttgl.setText("");
        cbjenis.setSelectedIndex(0);
        cbagama.setSelectedIndex(0);
        txtayah.setText("");
        cbayah.setSelectedIndex(0);
        txtibu.setText("");
        cbibu.setSelectedIndex(0);
        cbpdayah.setSelectedIndex(0);
        cbpdibu.setSelectedIndex(0);
        txtalamat.setText("");
        txttel.setText("");
        cbanak.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txttgl = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txttempat = new javax.swing.JTextField();
        cbibu = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtayah = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtibu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbanak = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        cbpdibu = new javax.swing.JComboBox<>();
        cbayah = new javax.swing.JComboBox<>();
        cbagama = new javax.swing.JComboBox<>();
        cbpdayah = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbjenis = new javax.swing.JComboBox<>();
        btnHapus = new javax.swing.JButton();
        btnDaftar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, java.awt.Color.white));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULIR PENDAFTARAN SISWA BARU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 30));

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setForeground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TK PELITA HARAPAN PG ASEMBAGUS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 770, 30));

        jLabel3.setFont(new java.awt.Font("Ink Free", 1, 13)); // NOI18N
        jLabel3.setText("No Telepon/HP :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 150, 30));

        jLabel4.setFont(new java.awt.Font("Ink Free", 1, 13)); // NOI18N
        jLabel4.setText("Nama Lengkap :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 130, 30));

        jLabel5.setFont(new java.awt.Font("Ink Free", 1, 13)); // NOI18N
        jLabel5.setText("Tempat Lahir :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 100, 30));

        jLabel6.setFont(new java.awt.Font("Ink Free", 1, 13)); // NOI18N
        jLabel6.setText("Tanggal Lahir :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 30));

        jLabel7.setFont(new java.awt.Font("Ink Free", 1, 13)); // NOI18N
        jLabel7.setText("Anak ke : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 70, 30));

        jLabel8.setFont(new java.awt.Font("Ink Free", 1, 13)); // NOI18N
        jLabel8.setText("Agama :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 100, 30));

        txttgl.setFont(new java.awt.Font("Ink Free", 1, 12)); // NOI18N
        jPanel1.add(txttgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 280, 30));

        txtalamat.setFont(new java.awt.Font("Ink Free", 1, 12)); // NOI18N
        jPanel1.add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 320, 80));

        txtnama.setFont(new java.awt.Font("Ink Free", 1, 12)); // NOI18N
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 280, 30));

        txttempat.setFont(new java.awt.Font("Ink Free", 1, 12)); // NOI18N
        jPanel1.add(txttempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 280, 30));

        cbibu.setBackground(new java.awt.Color(51, 51, 255));
        cbibu.setFont(new java.awt.Font("Ink Free", 1, 10)); // NOI18N
        cbibu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ibu Rumah Tangga", "Petani", "PNS(TNI/Polri/Guru)", "Pegawai Swasta", "Pegawai BUMN", "Wiraswasta", "Advokad", "Lainnya", " " }));
        jPanel1.add(cbibu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 170, 30));

        jLabel9.setFont(new java.awt.Font("Ink Free", 1, 13)); // NOI18N
        jLabel9.setText("Nama Ayah :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 110, 30));

        txtayah.setFont(new java.awt.Font("Ink Free", 1, 12)); // NOI18N
        jPanel1.add(txtayah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 280, 30));

        jLabel10.setFont(new java.awt.Font("Ink Free", 1, 13)); // NOI18N
        jLabel10.setText("Pekerjaan Ayah : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 150, 30));

        jLabel11.setFont(new java.awt.Font("Ink Free", 1, 13)); // NOI18N
        jLabel11.setText("Nama Ibu :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 110, 30));

        txtibu.setFont(new java.awt.Font("Ink Free", 1, 12)); // NOI18N
        jPanel1.add(txtibu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 280, 30));

        jLabel12.setFont(new java.awt.Font("Ink Free", 1, 13)); // NOI18N
        jLabel12.setText("Pekerjaan Ibu :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 150, 30));

        jLabel13.setFont(new java.awt.Font("Ink Free", 1, 13)); // NOI18N
        jLabel13.setText("Pend. Terakhir Ayah :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 150, 30));

        cbanak.setBackground(new java.awt.Color(51, 51, 255));
        cbanak.setFont(new java.awt.Font("Ink Free", 1, 10)); // NOI18N
        cbanak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", ">5" }));
        jPanel1.add(cbanak, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 60, 30));

        jLabel14.setFont(new java.awt.Font("Ink Free", 1, 13)); // NOI18N
        jLabel14.setText("Pend. Terakhir Ibu :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 150, 30));

        txttel.setFont(new java.awt.Font("Ink Free", 1, 12)); // NOI18N
        jPanel1.add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, 280, 30));

        jLabel15.setFont(new java.awt.Font("Ink Free", 1, 13)); // NOI18N
        jLabel15.setText("Alamat :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 150, 30));

        btnKembali.setBackground(new java.awt.Color(0, 153, 204));
        btnKembali.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(0, 0, 51));
        btnKembali.setText("Kembali");
        btnKembali.setBorder(null);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 630, 80, 30));

        cbpdibu.setBackground(new java.awt.Color(51, 51, 255));
        cbpdibu.setFont(new java.awt.Font("Ink Free", 1, 10)); // NOI18N
        cbpdibu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SD", "SMP", "SMA", "D1, D2, D3", "D4/S1", "S2", "S3" }));
        jPanel1.add(cbpdibu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 100, 30));

        cbayah.setBackground(new java.awt.Color(51, 51, 255));
        cbayah.setFont(new java.awt.Font("Ink Free", 1, 10)); // NOI18N
        cbayah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Petani", "PNS(TNI/Polri/Guru)", "Pegawai Swasta", "Pegawai BUMN", "Wiraswasta", "Advokad", "Lainnya", " " }));
        jPanel1.add(cbayah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 170, 30));

        cbagama.setBackground(new java.awt.Color(51, 51, 255));
        cbagama.setFont(new java.awt.Font("Ink Free", 1, 10)); // NOI18N
        cbagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam ", "Kristen Protestan", "Kristen Katolik", "Hindu", "Budha", "Konghucu" }));
        jPanel1.add(cbagama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 140, 30));

        cbpdayah.setBackground(new java.awt.Color(51, 51, 255));
        cbpdayah.setFont(new java.awt.Font("Ink Free", 1, 10)); // NOI18N
        cbpdayah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SD", "SMP", "SMA", "D1, D2, D3", "D4/S1", "S2", "S3" }));
        jPanel1.add(cbpdayah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 100, 30));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        jLabel17.setFont(new java.awt.Font("Ink Free", 1, 13)); // NOI18N
        jLabel17.setText("Jenis Kelamin :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, 30));

        cbjenis.setBackground(new java.awt.Color(51, 51, 255));
        cbjenis.setFont(new java.awt.Font("Ink Free", 1, 10)); // NOI18N
        cbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        jPanel1.add(cbjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 140, 30));

        btnHapus.setBackground(new java.awt.Color(0, 153, 204));
        btnHapus.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(0, 0, 51));
        btnHapus.setText("...");
        btnHapus.setBorder(null);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 80, 30));

        btnDaftar.setBackground(new java.awt.Color(0, 153, 204));
        btnDaftar.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        btnDaftar.setForeground(new java.awt.Color(0, 0, 51));
        btnDaftar.setText("Daftar");
        btnDaftar.setBorder(null);
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 790, 680));

        setSize(new java.awt.Dimension(828, 736));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
     dashboard dsb= new dashboard();
                dsb.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    
    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
    try{
        sql ="INSERT INTO `pendaftaran`(`namalengkap`, `tempatlahir`, `tanggallahir`, `jeniskel`, `agama`, `namaAyah`, `pekAyah`, `namaIbu`, `pekIbu`, `PendAyah`, `PendIbu`, `alamat`, `telepon`, `anakke`) VALUES('"+txtnama.getText()+ "','" +txttempat.getText()+"','"+ txttgl.getText()+"','"+cbjenis.getSelectedItem()+"','"+cbagama.getSelectedItem()+"','"+txtayah.getText()+"','"+cbayah.getSelectedItem()+"','"+txtibu.getText()+"','"+cbibu.getSelectedItem()+"','"+cbpdayah.getSelectedItem()+"','"+cbpdibu.getSelectedItem()+"','"+txtalamat.getText()+"','"+txttel.getText()+"','"+cbanak.getSelectedItem()+"')";
        int row = state.executeUpdate(sql);
            
        if(row==1){
        JOptionPane.showMessageDialog(null, "Pendaftaran Peserta Didik Baru Berhasil");
        con.close();
        hapuslayar();
        }
            
    }catch (SQLException e){
        JOptionPane.showMessageDialog(null, "Gagal Mendaftar" + e);
    }
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed

    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pendaftaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JComboBox<String> cbagama;
    private javax.swing.JComboBox<String> cbanak;
    private javax.swing.JComboBox<String> cbayah;
    private javax.swing.JComboBox<String> cbibu;
    private javax.swing.JComboBox<String> cbjenis;
    private javax.swing.JComboBox<String> cbpdayah;
    private javax.swing.JComboBox<String> cbpdibu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtayah;
    private javax.swing.JTextField txtibu;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField txttempat;
    private javax.swing.JTextField txttgl;
    // End of variables declaration//GEN-END:variables
}
